/**
 * Bearer-key authentication for the MCP endpoint. A valid, non-revoked API
 * key is the whole gate - the product is free, so there is no entitlement
 * lookup behind the key, only "does this key exist and is it still live".
 *
 * Reuses rather than copies: `hashApiKey` from
 * app/src/lib/workspace/api-keys.ts (the same SHA-256-then-hex the dashboard
 * uses to create a key, so a key minted there verifies here with no format
 * drift) and the `mcpKey`/D1 access from app/src/db/schema.ts + client.ts.
 * All read-only imports - this file does not write to any app/src file, so
 * the app's own build and `astro check` are untouched by this package
 * existing.
 *
 * The one query app/src/lib/workspace/api-keys.ts does not have -
 * "look up a key row by its hash, regardless of owner" - is written directly
 * against the reused `mcpKey` schema below rather than added to that file,
 * for the same untouched-app reason.
 */

import { eq } from "drizzle-orm";
import {
  OAuthError,
  OAuthErrorCode,
  type AuthInfo,
  type OAuthTokenVerifier,
} from "@modelcontextprotocol/server";
import { db } from "../../app/src/db/client";
import { mcpKey } from "../../app/src/db/schema";
import { API_KEY_PREFIX, hashApiKey } from "../../app/src/lib/workspace/api-keys";

/* `Env` is ambient (see worker-configuration.d.ts, generated by `pnpm run
   types` from wrangler.jsonc) - no import needed, same as `Request`/
   `Response` below. */

/** One message for every failure mode (missing header, malformed header,
    unknown hash, revoked key) - not just brevity, it also means a bad key
    and someone else's revoked key look identical to a caller, so this is not
    an oracle for probing which keys exist. */
const AUTH_REQUIRED_MESSAGE =
  "This MCP server needs an API key. Create a free account at motificons.app and generate a key in your dashboard.";

/** mk_ keys are permanent until revoked (no expiry field on the row) - the
    bearer-auth contract still requires `expiresAt`, so this is a far-future
    stand-in rather than a real deadline. */
const FAR_FUTURE_EXPIRY = Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365 * 100;

/** Threaded through `AuthInfo.extra` into every tool call via the request's
    `McpServerFactory` closure (see src/server.ts) - the identity a
    collection-scoped tool needs. */
export interface MotificonsAuthExtra {
  userId: string;
  workspaceId: string;
  keyId: string;
  [key: string]: unknown;
}

function verifier(): OAuthTokenVerifier {
  return {
    async verifyAccessToken(token: string): Promise<AuthInfo> {
      if (!token.startsWith(API_KEY_PREFIX)) {
        throw new OAuthError(OAuthErrorCode.InvalidToken, AUTH_REQUIRED_MESSAGE);
      }

      const keyHash = await hashApiKey(token);
      const database = await db();
      const rows = await database
        .select()
        .from(mcpKey)
        .where(eq(mcpKey.keyHash, keyHash))
        .limit(1);
      const row = rows[0];

      if (!row || row.revokedAt) {
        throw new OAuthError(OAuthErrorCode.InvalidToken, AUTH_REQUIRED_MESSAGE);
      }

      const extra: MotificonsAuthExtra = {
        userId: row.userId,
        workspaceId: row.workspaceId,
        keyId: row.id,
      };

      return {
        token,
        clientId: row.userId,
        scopes: ["mcp"],
        expiresAt: FAR_FUTURE_EXPIRY,
        extra,
      };
    },
  };
}

export type AuthResult =
  | { ok: true; auth: AuthInfo }
  | { ok: false; message: string };

/**
 * The full gate: parses `Authorization`, verifies the token, and always
 * resolves (never throws) - `ok: false` carries the one plain-language
 * message every failure mode shares. The caller (src/index.ts) turns that
 * into the JSON-RPC error response; this function stays transport-agnostic
 * so it is unit-testable without constructing a `Request`.
 */
export async function authenticate(
  authorizationHeader: string | null,
): Promise<AuthResult> {
  if (!authorizationHeader) return { ok: false, message: AUTH_REQUIRED_MESSAGE };

  const [scheme, token] = authorizationHeader.split(" ");
  if (scheme?.toLowerCase() !== "bearer" || !token) {
    return { ok: false, message: AUTH_REQUIRED_MESSAGE };
  }

  try {
    const auth = await verifier().verifyAccessToken(token);
    return { ok: true, auth };
  } catch (error) {
    if (error instanceof OAuthError) return { ok: false, message: error.message };
    throw error;
  }
}

export { AUTH_REQUIRED_MESSAGE };
